### PR TITLE
Update to release 1.1.0

### PR DESCRIPTION
**Pull request by constantinpape**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by constantinpape** [comment]
@conda-forge-admin, please rerender

**Comment by SylvainCorlay** [comment]
z5py does not work with the latest xtensor?

**Comment by constantinpape** [comment]
yes, it's still the import error with `xtl` in `xtensor-python`.
If I have time later I will try to find a minimal example and re-open the issue in `xtensor-python`.

**Comment by SylvainCorlay** [comment]
Do you want to hop on gitter.im/QuantStack/Lobby to chat about this real quick?

**Comment by constantinpape** [comment]
Added @SylvainCorlay to maintainers; as discussed on xtensor gitter

**Comment by SylvainCorlay** [comment]
👍

**Pull request merged**
