### PR TITLE
Change blosc package

### LINKED ISSUE #1: Change c-blosc to blosc
Missed this in review, sorry. We should change `c-blosc` to `blosc` in the recipe. The latter is how it is named in `conda-forge`.

https://github.com/conda-forge/z5py-feedstock/blob/1e9d0a615a0fff2414feec564432d2a03d6ff314/recipe/meta.yaml#L28

### PR DESCRIPTION
**Pull request by constantinpape**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [X] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Fixes #1

### CODE REVIEW

**Comment by constantinpape** [comment]
<code>@<space/>conda-forge-admin, please rerender</code>

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by jakirkham** [comment]
The html space part is added to the OP to avoid accidentally triggering the bot.

**Comment by constantinpape** [comment]
ok, got it

**Pull request merged**
