### PR TITLE
Update to new release; drop py2; use std::filesystem

### LINKED ISSUE #15: Boost 1.70
The build with boost 1.70 does not work due to a linker error with boost filesystem.
1.69 does work and we use it for now. See #13 for details.

### PR DESCRIPTION
**Pull request by constantinpape**
Fixes #15

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by constantinpape** [comment]
@conda-forge-admin, please rerender

**Comment by constantinpape** [comment]
The osx build is failing with a linker error somehow related to stdc++experimental:
```
Traceback (most recent call last):
  File "/usr/local/miniconda/conda-bld/z5py_1565187741253/test_tmp/run_test.py", line 2, in <module>
    import z5py
...
Symbol not found: __ZNKSt12experimental10filesystem2v118directory_iterator7__derefEv
```
I tried to fix this with [this patch](https://github.com/conda-forge/z5py-feedstock/blob/2affd8e1e008a1fd3526fae97bf72916088feceb/recipe/patches/link_experimental_clang.patch) but it did not help.
Any ideas, @stuarteberg?

**Comment by stuarteberg** [comment]
I can reproduce the error, and fix it with a new patch.  See https://github.com/constantinpape/z5/pull/128

**Comment by constantinpape** [comment]
> I can reproduce the error, and fix it with a new patch. See [constantinpape/z5#128](https://github.com/constantinpape/z5/pull/128)

Thanks for looking into this.
I have merged your PR and moved the release tag.

Let's hope all builds run through now.

**Comment by stuarteberg** [comment]
Nice.  Thanks!

**Pull request merged**
